### ISSUE TITLE
RC7 Revo Spektrum

### ISSUE THREAD

**Issue by JasonB91** [rs2k/raceflight#101]
Unable to view RC Command, and live graph just freezes. Additionally, AUX Maps are unable to function. Worked fine with RC5 build (OPBL). Full size Revo.

**Comment by proggod** [comment]
Please test betas and see if this issue is in any of them, closing this issue since its based on an old version of our binaries, if you want access to betas please join our group at https://www.facebook.com/groups/1023175947742218/

Just trying to get github cleaned up so people can report issues with our betas....
