### ISSUE TITLE
REVO nano - PWM parralel problems 

### ISSUE THREAD

**Issue by zipray** [rs2k/raceflight#171]
Tried enabling/disabling VBAT, all different mappings of RC channels in Configurator...but It is not working.（DEVO7E and RX601)

**Comment by proggod** [comment]
What isn't working, vbat or something else?

**Comment by zipray** [comment]
All Channels status bar no move,That  connection correct.because OP firmware is normal.

**Comment by proggod** [comment]
Please test betas and see if this issue is in any of them, closing this issue since its based on an old version of our binaries, if you want access to betas please join our group at https://www.facebook.com/groups/1023175947742218/

Just trying to get github cleaned up so people can report issues with our betas....
