### ISSUE TITLE
Airmode ignores yaw

### ISSUE THREAD

**Issue by Jahnkeanater** [rs2k/raceflight#174]
When at low throttle airmode does not increase the throttle to do yaw maneuvers like it should.
This is only an issue at very low throttle. Even the slightest amount of throttle results in a good amount of yaw authority.

At less than ~10% throttle airmode needs to factor in yaw.

**Comment by proggod** [comment]
Please test betas and see if this issue is in any of them, closing this issue since its based on an old version of our binaries, if you want access to betas please join our group at https://www.facebook.com/groups/1023175947742218/

Just trying to get github cleaned up so people can report issues with our betas....
