### ISSUE TITLE
No stabilization in 3d deadband when returning from a low state. 

### ISSUE THREAD

**Issue by MrKarver** [rs2k/raceflight#194]
In 3d only and tested under Air Mode and Always Stabilized. 

The problem is when returning back to deadband from a low stick to mid stick position. And only while in the deadband area all stabilization stops working. The quad goes limp..  Once you pass back into high throttle area it works again. So only in deadband and only from low stick to mid-stick deadband. 

I hope that makes sense. I tested this in Betaflight 2.6.1 as well 2.7 and in both revisions  stabilization remains at all times. In and out of deadband going both directions. 

Thank you

**Comment by proggod** [comment]
3d is not supported but will be in upcoming betas, closing this issue since its based on an old version of our binaries, if you want access to betas please join our group at https://www.facebook.com/groups/1023175947742218/

Just trying to get github cleaned up so people can report issues with our betas....
