### ISSUE TITLE
Motors spin up when disarmed.

### ISSUE THREAD

**Issue by Jahnkeanater** [rs2k/raceflight#196]
When arming with a switch if you turn the transmitter off before the quad the motors spin up for a split second. This may have something to do with my failsafe throttle being set to 1200.

Failsafe code should not run when disarmed.

RC12 release

**Comment by proggod** [comment]
Please test betas and see if this issue is in any of them, closing this issue since its based on an old version of our binaries, if you want access to betas please join our group at https://www.facebook.com/groups/1023175947742218/

Just trying to get github cleaned up so people can report issues with our betas....
