### ISSUE TITLE
Implement LRS Support on Sparky 2

### ISSUE THREAD

**Issue by brat002** [rs2k/raceflight#78]
It will be great if Raceflight will support RFM22b module that comes with Sparky 2.

**Comment by blckmn** [comment]
Would the module be of much value racing?

**Comment by brat002** [comment]
This module saves place and AUW. Sparky 2 has one reciever. Why we need additonal one?

**Comment by chocol4te** [comment]
I am relatively familiar with the OpenLRSng code, and will be happy to work on this feature, but it might be a while before I can buy a Sparky 2.

**Comment by brycedjohnson** [comment]
Might be able to get a lower latency tx link by using spi and the RFM22b instead of sbus. Also would need  the opernlrsng to support a serial protocol such as this for opentx (https://github.com/opentx/opentx/issues/2894)

**Comment by Linjieqiang** [comment]
This feature sounds nice~

**Comment by brat002** [comment]
I am still waiting this feature to flash Raceflight into my Sparky 2.

**Comment by proggod** [comment]
Please test betas and see if this issue is in any of them, closing this issue since its based on an old version of our binaries, if you want access to betas please join our group at https://www.facebook.com/groups/1023175947742218/

Just trying to get github cleaned up so people can report issues with our betas....
